mpi:
  - mpich
#  - openmpi # https://github.com/deepmodeling/abacus-develop/issues/5194

# follow pytorch's pin
c_stdlib_version:  # [unix]
  - 2.28           # [linux and aarch64]
  - 10.15          # [osx and x86_64]
